In [39]:
#****************
#change all these except for BUCKET_LOC
#****************
PROJECT_ID = 'ml-demo-384110'
DATASET_ID = 'bqml_tutorial_us'
OJBECT_TABLE_NAME= 'obj_cloud_ai_images'
CONN_NAME= 'conn_cloud_ai'
CONN_SERVICE_ACCOUNT = ""
REGION = "US"
VISION_MODEL_NAME = 'bqml-cloud-ai-vision'
TRANSLATE_MODEL_NAME = 'bqml-cloud-ai-translate'
TEXT_MODEL_NAME = 'bqml-cloud-ai-text'
LLM_TEXT_MODEL_NAME = 'bqml-llm_model'


Demo of BQML cloud-ai API functionality.

Objective of Demo:  Using unstructured data in BQ Data Analytics workflows

Main steps:
1.   create object table
2.   Call vision ai (ML.ANNOTATE_IMAGE) to do OCR
3.   Call translate ai (ML.TRANSLATE) to detect language of text
4.   Call translate ai (ML.TRANSLATE) to translate non-english records to english
5.   Call NLP ai (ML.UNDERSTAND_TEXT) to classify text
6.   Call text-bison LLM model (ML.GENERATE_TEXT) more detail here: https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-generate-text

In [12]:
!pip install google-cloud-bigquery-connection
from google.cloud import bigquery, bigquery_connection_v1

WARNING: Ignoring invalid distribution -oogle-auth (/opt/conda/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -oogleapis-common-protos (/opt/conda/lib/python3.10/site-packages)
Requirement already satisfied: google-cloud-bigquery-connection in /opt/conda/lib/python3.10/site-packages (1.12.1)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0 in /home/jupyter/.local/lib/python3.10/site-packages (from google-cloud-bigquery-connection) (1.34.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery-connection) (1.22.2)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /home/jupyter/.local/lib/python3.10/site-packages (from google-cloud-bigquery-connection) (3.20.3)
Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery-connection) (0.12.6)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /home/jupyter/.local/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (1.59.1)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (1.35.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/jupyter/.local/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (2.31.0)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (1.51.3)
Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (1.48.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/jupyter/.local/lib/python3.10/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (4.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/jupyter/.local/lib/python3.10/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (0.3.0)
Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.10/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (67.7.2)
Requirement already satisfied: six>=1.9.0 in /home/jupyter/.local/lib/python3.10/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/jupyter/.local/lib/python3.10/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (4.9)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jupyter/.local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyter/.local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyter/.local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyter/.local/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (2023.5.7)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/jupyter/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.0->google-cloud-bigquery-connection) (0.5.0)
WARNING: Ignoring invalid distribution -oogle-auth (/opt/conda/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -oogleapis-common-protos (/opt/conda/lib/python3.10/site-packages)

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

In [3]:
!gcloud config set project {PROJECT_ID}
shell_output = ! gcloud config list --format 'value(core.project)' 2>/dev/null
PROJECT_ID = shell_output[0]
print("Project ID now set to:", PROJECT_ID)

Updated property [core/project].
Project ID now set to: ml-demo-384110

In [4]:
#you may need to enable apis
!gcloud services enable vision.googleapis.com language.googleapis.com

Operation "operations/acat.p2-1008225662928-764e721b-65bb-43ff-9a67-7d0ba5c21622" finished successfully.

In [26]:
#Create BQ Connection
from google.cloud import bigquery as bq
from google.cloud import bigquery_connection_v1 as bq_connection
import googleapiclient.discovery

client = bq_connection.ConnectionServiceClient()
new_conn_parent="projects/{}/locations/{}".format(PROJECT_ID, "US")
exists_conn_parent="projects/{}/locations/{}/connections/{}".format(PROJECT_ID, "US", CONN_NAME)
cloud_resource_properties = bq_connection.CloudResourceProperties({})

try:
  request = client.get_connection(request=bq_connection.GetConnectionRequest(name=exists_conn_parent))
  CONN_SERVICE_ACCOUNT = "serviceAccount:{}".format(request.cloud_resource.service_account_id)
except Exception as e:
  connection = bq_connection.types.Connection(
          {
              "friendly_name": CONN_NAME,
              "cloud_resource": cloud_resource_properties
          }
      )
  request = bq_connection.CreateConnectionRequest(
          {
              "parent": new_conn_parent,
              "connection_id": CONN_NAME,
              "connection": connection
          }
      )
  response = client.create_connection(request)
  CONN_SERVICE_ACCOUNT = "serviceAccount:{}".format(response.cloud_resource.service_account_id)
print(CONN_SERVICE_ACCOUNT)

serviceAccount:bqcx-1008225662928-osik@gcp-sa-bigquery-condel.iam.gserviceaccount.com

In [27]:
!gcloud projects add-iam-policy-binding {PROJECT_ID} --condition=None --no-user-output-enabled --member={CONN_SERVICE_ACCOUNT} --role='roles/serviceusage.serviceUsageConsumer'

In [28]:
!gcloud projects add-iam-policy-binding {PROJECT_ID} --condition=None --no-user-output-enabled --member={CONN_SERVICE_ACCOUNT} --role='roles/bigquery.connectionUser'

In [29]:
!gcloud projects add-iam-policy-binding {PROJECT_ID} --condition=None --no-user-output-enabled --member={CONN_SERVICE_ACCOUNT}  --role='roles/cloudtranslate.user'

In [31]:
#create object table
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = f"""
          CREATE OR REPLACE EXTERNAL TABLE
          `{PROJECT_ID}.{DATASET_ID}.{OJBECT_TABLE_NAME}`
          WITH CONNECTION `{REGION}.{CONN_NAME}` OPTIONS( object_metadata = 'SIMPLE',
          uris = ['gs://data-analytics-demos/TextOCR_images/*']);
          """ 
        
    query_job = client.query(sql)
    results = query_job.result()

except Exception as e:
    raise Exception(str(e))

In [33]:
#query object table
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = f"""
      SELECT * FROM
      `{PROJECT_ID}.{DATASET_ID}.{OJBECT_TABLE_NAME}` limit 50 ;
      """
  
    df = client.query(sql).to_dataframe()

except Exception as e:
    raise Exception(str(e))

df.head(6)

,uri,generation,content_type,size,md5_hash,updated,metadata
0,gs://data-analytics-demos/TextOCR_images/00875...,1680039280565689,image/jpeg,766494,b20ee2f0609a75e4ba95666893a1ba8c,2023-03-28 21:34:40.607000+00:00,[]
1,gs://data-analytics-demos/TextOCR_images/01023...,1680039280553219,image/jpeg,824430,51911a441d0213f3f644b4c092ceb137,2023-03-28 21:34:40.605000+00:00,[]
2,gs://data-analytics-demos/TextOCR_images/0328f...,1680039280563977,image/jpeg,747167,dec21a8a7cb426272eb7cf2739cfde06,2023-03-28 21:34:40.605000+00:00,[]
3,gs://data-analytics-demos/TextOCR_images/04b03...,1680039280568388,image/jpeg,702377,87f32af89141a6269501dd285ac6699c,2023-03-28 21:34:40.608000+00:00,[]
4,gs://data-analytics-demos/TextOCR_images/07901...,1680039280574171,image/jpeg,851695,16886737338012a0e556e8331eba7f8a,2023-03-28 21:34:40.609000+00:00,[]
5,gs://data-analytics-demos/TextOCR_images/08d54...,1680039280676556,image/jpeg,815716,427c6695e732898c8606c1ec2f21cf8f,2023-03-28 21:34:40.708000+00:00,[]

In [41]:
#create vision api model
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = """
      CREATE OR REPLACE MODEL `{PROJECT_ID}.{DATASET_ID}.{VISION_MODEL_NAME}`
      REMOTE WITH CONNECTION `{PROJECT_ID}.{REGION}.{CONN_NAME}`
      OPTIONS (
        remote_service_type = 'cloud_ai_vision_v1');
      """.format(PROJECT_ID = PROJECT_ID,DATASET_ID = DATASET_ID, OJBECT_TABLE_NAME=OJBECT_TABLE_NAME, VISION_MODEL_NAME=VISION_MODEL_NAME, REGION=REGION, CONN_NAME=CONN_NAME)
    query_job = client.query(sql)
    results = query_job.result()

    model_id = '{}.{}.{}'.format(PROJECT_ID, DATASET_ID, VISION_MODEL_NAME)

    model = client.get_model(model_id)  # Make an API request.

    full_model_id = "{}.{}.{}".format(model.project, model.dataset_id, model.model_id)
    friendly_name = model.friendly_name
    print(
      "Vision Model now available '{}'".format(full_model_id, friendly_name)
  )
except Exception as e:
    raise Exception(str(e))

Vision Model now available 'ml-demo-384110.bqml_tutorial_us.bqml-cloud-ai-vision'

In [35]:
#create translate api model
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = """
      CREATE OR REPLACE MODEL
      `{}.{}.{}` REMOTE
      WITH CONNECTION `{}.{}.{}`
      OPTIONS ( remote_service_type = 'CLOUD_AI_TRANSLATE_V3');
      """.format(PROJECT_ID,DATASET_ID, TRANSLATE_MODEL_NAME,PROJECT_ID, REGION, CONN_NAME)
    query_job = client.query(sql)
    results = query_job.result()

    model_id = '{}.{}.{}'.format(PROJECT_ID, DATASET_ID, TRANSLATE_MODEL_NAME)

    model = client.get_model(model_id)  # Make an API request.

    full_model_id = "{}.{}.{}".format(model.project, model.dataset_id, model.model_id)
    friendly_name = model.friendly_name
    print(
    "Translate Model now available '{}'".format(full_model_id, friendly_name)
  )

except Exception as e:
    raise Exception(str(e))

Translate Model now available 'ml-demo-384110.bqml_tutorial_us.bqml-cloud-ai-translate'

In [36]:
#create NLP model
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = """
      CREATE OR REPLACE MODEL
      `{}.{}.{}` REMOTE
      WITH CONNECTION `{}.{}.{}`
      OPTIONS ( remote_service_type = 'cloud_ai_natural_language_v1');
      """.format(PROJECT_ID,DATASET_ID, TEXT_MODEL_NAME,PROJECT_ID, REGION, CONN_NAME)
    query_job = client.query(sql)
    results = query_job.result()

    model_id = '{}.{}.{}'.format(PROJECT_ID, DATASET_ID, TEXT_MODEL_NAME)

    model = client.get_model(model_id)  # Make an API request.

    full_model_id = "{}.{}.{}".format(model.project, model.dataset_id, model.model_id)
    friendly_name = model.friendly_name
    print(
    "NLP Model now available '{}'".format(full_model_id, friendly_name)
  )

except Exception as e:
    raise Exception(str(e))

NLP Model now available 'ml-demo-384110.bqml_tutorial_us.bqml-cloud-ai-text'

In [37]:
#Use vision ai to get text from images
#then use translate ai to check language of text
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = """
        CREATE OR REPLACE TABLE
          `{}.{}.temp_image_results` AS
        SELECT
          --this column must be aliased/named 'text_content'
          STRING(ml_annotate_image_result.full_text_annotation.text) AS text_content
        FROM
          ML.ANNOTATE_IMAGE( MODEL `{}.{}.{}`,
            TABLE `{}.{}.{}`,
            STRUCT(['TEXT_DETECTION'] AS vision_features));

        CREATE OR REPLACE TABLE {}.{}.temp_detect_language_results as
        SELECT
          ml_translate_result.languages[0].language_code,
          ml_translate_result.languages[0].confidence, *
        FROM
          ML.TRANSLATE( MODEL `{}.{}.{}`, TABLE `{}.{}.temp_image_results`, STRUCT("detect_language" AS translate_mode));

        SELECT * FROM {}.{}.temp_detect_language_results;
        """.format(PROJECT_ID, DATASET_ID, PROJECT_ID, DATASET_ID, VISION_MODEL_NAME, PROJECT_ID, DATASET_ID, OJBECT_TABLE_NAME, PROJECT_ID, DATASET_ID, PROJECT_ID, DATASET_ID, TRANSLATE_MODEL_NAME, PROJECT_ID,DATASET_ID, PROJECT_ID, DATASET_ID )

    df = client.query(sql).to_dataframe()

except Exception as e:
    raise Exception(str(e))



df.head(6)

,language_code,confidence,ml_translate_result,ml_translate_status,text_content
0,"""ar""",1,"{""languages"":[{""confidence"":1,""language_code"":...",,فة، لم يكن حولها جدار\nبا دور للناس، وإنما كان...
1,"""de""",0.88780957,"{""languages"":[{""confidence"":0.88780957,""langua...",,TI\nVifebook!\n9\noh\nhein!\nDIR\nfreice Tag: ...
2,"""de""",1,"{""languages"":[{""confidence"":1,""language_code"":...",,Alleinige Inseraten-Annahme\nbei Rudolf Mosse\...
3,"""de""",0.39134026,"{""languages"":[{""confidence"":0.39134026,""langua...",,"Rainhard Fendrich Rainhard Fendrich, Katie Mel..."
4,"""de""",0.96768254,"{""languages"":[{""confidence"":0.96768254,""langua...",,PRICKELMA\nCLUB-MATE\nSCHE\nMATE\nDe in des\nw...
5,"""de""",0.29555309,"{""languages"":[{""confidence"":0.29555309,""langua...",,O\n12\nΩ\nOMEGA\nSeamaster\nPROFESSIONAL\nAXIA...

In [ ]:
#use translate ai to translate text
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = """
        SELECT text_content, language_code,
          ml_translate_result.translations[0].translated_text
        FROM
          ML.TRANSLATE( MODEL `{}.{}.{}`, TABLE `{}.{}.temp_detect_language_results`, STRUCT("translate_text" as translate_mode, "en" as target_language_code));
        """.format( PROJECT_ID,DATASET_ID, TRANSLATE_MODEL_NAME, PROJECT_ID,DATASET_ID)

    df = client.query(sql).to_dataframe()

except Exception as e:
    raise Exception(str(e))

df.head(6)

,text_content,language_code,translated_text
0,فة، لم يكن حولها جدار\nبا دور للناس، وإنما كان...,"""ar""","""There was no wall around it with no role for ..."
1,PRICKELMA\nCLUB-MATE\nSCHE\nMATE\nDe in des\nw...,"""de""","""PRICKELMA CLUB-MATE SCHE MATE De in des wwwww..."
2,F FÜR TRÄUME\nFortsetzung von Seite 304\nDie K...,"""de""","""F FOR DREAMS Continued from page 304 The cham..."
3,O\n12\nΩ\nOMEGA\nSeamaster\nPROFESSIONAL\nAXIA...,"""de""","""O 12Ω OMEGA Seamaster PROFESSIONAL AXIAL HOME..."
4,Alleinige Inseraten-Annahme\nbei Rudolf Mosse\...,"""de""","""Sole acceptance of advertisements at Rudolf M..."
5,TI\nVifebook!\n9\noh\nhein!\nDIR\nfreice Tag: ...,"""de""","""TI Vibook! 9 oh hey! DIR freice day: Think ™R..."
6,"Rainhard Fendrich Rainhard Fendrich, Katie Mel...","""de""","""Rainhard Fendrich Rainhard Fendrich, Katie Me..."
7,Reaktionen im Netz\nLifestream Termine Die Ini...,"""de""","""Reactions on the web Lifestream Dates The ini..."
8,WÜNSCHEN SIE ERSTKLASSIGE\nTAPETEN\nDER NEUEN ...,"""de""","""WANT NEW SEASON PREMIUM WALLPAPERS. HOW TO AS..."
9,THE CLOISTERS WETLAND\nThe wetland you see her...,"""en""","""THE CLOISTERS WETLAND\nThe wetland you see he..."
10,"Gayatri Mantra\nOm\nUnderworld, Earth and Heav...","""en""","""Gayatri Mantra\nOm\nUnderworld, Earth and Hea..."
11,Tell HTC\nEnroll in Tell HTC\nHelp us improve ...,"""en""","""Tell HTC\nEnroll in Tell HTC\nHelp us improve..."
12,A\nGOOD\nYEAR\n•\nBY BRAD MELTZER\nPETER\nMAYL...,"""en""","""A\nGOOD\nYEAR\n•\nBY BRAD MELTZER\nPETER\nMAY..."
13,try factory where UN peacekeepers were sta-\nt...,"""en""","""try factory where UN peacekeepers were sta-\n..."
14,Ica-Colica Collca-Colca Col\nzero zero zero ze...,"""en""","""Ica-Colica Collca-Colca Col\nzero zero zero z..."
15,OF\nANIMAL\nCAL POLY\nSTATE UNIV\nS.L.O.\nACTI...,"""en""","""OF\nANIMAL\nCAL POLY\nSTATE UNIV\nS.L.O.\nACT..."
16,CAMBODIA/CHINA\nOver 60 million people depend ...,"""en""","""CAMBODIA/CHINA\nOver 60 million people depend..."
17,Inferno\nThe Glass Books of the Dream Eaters\n...,"""en""","""Inferno\nThe Glass Books of the Dream Eaters\..."
18,204PWAR\n2 COMPLETE ARMIES\nEVERY PIECE OF PUR...,"""en""","""204PWAR\n2 COMPLETE ARMIES\nEVERY PIECE OF PU..."
19,AS\nAdded\nLegmans\nFood You Feel Good\nWegman...,"""en""","""AS\nAdded\nLegmans\nFood You Feel Good\nWegma..."
20,"se, a fugue or\non but are all\nrisingly, sinc...","""en""","""se, a fugue or\non but are all\nrisingly, sin..."
21,ICDecaux\nMilnrow Road\nTravis Street\nBus Tim...,"""en""","""ICDecaux\nMilnrow Road\nTravis Street\nBus Ti..."
22,a live\nRIL&17 MAY 6.30-9.30PM\nNE 6.30-10.00P...,"""en""","""a live\nRIL&17 MAY 6.30-9.30PM\nNE 6.30-10.00..."
23,"West Nile Virus\nNicole Burns, Valerie Howell,...","""en""","""West Nile Virus\nNicole Burns, Valerie Howell..."
24,JUHTA TRAVELLER Italo Calvino\nlan Kundera\nND...,"""en""","""JUHTA TRAVELLER Italo Calvino\nlan Kundera\nN..."
25,VICTOR\nFRANCENSTEIN\nMBRAPES AND OAK BARREL A...,"""en""","""VICTOR\nFRANCENSTEIN\nMBRAPES AND OAK BARREL ..."
26,DIY FASHIONISTA\nLAUREN CONRAD\nDIY FASHIONIST...,"""en""","""DIY FASHIONISTA\nLAUREN CONRAD\nDIY FASHIONIS..."
27,244\nCHAPTER 7: The Derivative\n(b) Hence find...,"""en""","""244\nCHAPTER 7: The Derivative\n(b) Hence fin..."
28,STAR\nImported\nFirst Cold Press\nwwwwwww\nEXT...,"""en""","""STAR\nImported\nFirst Cold Press\nwwwwwww\nEX..."
29,THE CORSICAN CAPER\nlove at first bite. Elena ...,"""en""","""THE CORSICAN CAPER\nlove at first bite. Elena..."
30,"phia in April 1775,\ntia and began drilling on...","""en""","""phia in April 1775,\ntia and began drilling o..."
31,IS A CHOLESTEROL\nFOOD WITH 140 OF\nALFAT PER ...,"""en""","""IS A CHOLESTEROL\nFOOD WITH 140 OF\nALFAT PER..."
32,TRA\nANTI-SLAVERY\nCELEBRATION!\nFIRST OF AUGU...,"""en""","""TRA\nANTI-SLAVERY\nCELEBRATION!\nFIRST OF AUG..."
33,Silent\nAuction\nWin this...\nPieced Wall Hang...,"""en""","""Silent\nAuction\nWin this...\nPieced Wall Han..."
34,Bryce Canyon National Park\nLodge\n♦\n0.5 mi\n...,"""en""","""Bryce Canyon National Park\nLodge\n♦\n0.5 mi\..."
35,GIANTS\n軍\nShawn Estes\nSAN FRANCISCO GIANTS: ...,"""en""","""GIANTS\n軍\nShawn Estes\nSAN FRANCISCO GIANTS:..."
36,MALARIA! -\nMORRISSEY -\nNITZER 666.\nVOLTAIRE...,"""en""","""MALARIA! -\nMORRISSEY -\nNITZER 666.\nVOLTAIR..."
37,TOLOILO Literary Criticism\nTCLC 128 Literary ...,"""en""","""TOLOILO Literary Criticism\nTCLC 128 Literary..."
38,COMPANY B\n126M AGM 505 IME VE\nAbove: Aboord ...,"""en""","""COMPANY B\n126M AGM 505 IME VE\nAbove: Aboord..."
39,x commodore\n1541\nWOE\n(O eommodore\nTA\nP\nS...,"""en""","""x commodore\n1541\nWOE\n(O eommodore\nTA\nP\n..."
40,O\n1772\n2012\n07:0\nCOMPLETE\nHISTORY OF DRIN...,"""en""","""O\n1772\n2012\n07:0\nCOMPLETE\nHISTORY OF DRI..."
41,fr\nAn Epitaph\nThe Register of this Parish\nB...,"""en""","""fr\nAn Epitaph\nThe Register of this Parish\n..."
42,Number of sheets to\nblock the pretend space\n...,"""en""","""Number of sheets to\nblock the pretend space\..."
43,of photograph\n200 Partie\nDj Ders\npent\nat\n...,"""en""","""of photograph\n200 Partie\nDj Ders\npent\nat\..."
44,US-ASEAN\nBUSINESS COUNCIL IN\nONE\nFULLERTON\...,"""en""","""US-ASEAN\nBUSINESS COUNCIL IN\nONE\nFULLERTON..."
45,Blogs History Going out Shopping & services Co...,"""en""","""Blogs History Going out Shopping & services C..."
46,ACK HIGGINS\nto the way to manag\nAt McNally's...,"""en""","""ACK HIGGINS\nto the way to manag\nAt McNally'..."
47,Airport\nBusiness\n기\nunagroup\nCentre\nPlymou...,"""en""","""Airport\nBusiness\n기\nunagroup\nCentre\nPlymo..."
48,YOUR FREE TRIP\n...AND WHEN WE GOT TO THE TOP ...,"""en""","""YOUR FREE TRIP\n...AND WHEN WE GOT TO THE TOP..."
49,Distinct X Line connects all plywood. With suc...,"""en""","""Distinct X Line connects all plywood. With su..."

In [38]:
#create object table
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = """
      SELECT
      text_content AS `Original Input`,
      replace(string(ml_understand_text_result.categories[0].name), '/','') AS `Classified Name`,
      ml_understand_text_result.categories[0].confidence AS `Confidence`
      FROM
      ML.UNDERSTAND_TEXT( MODEL `{}.{}.{}`,
        TABLE `{}.{}.temp_detect_language_results`,
        STRUCT('classify_text' AS nlu_option))
        where  ml_understand_text_result.categories[0].name is not null ;
      """.format(PROJECT_ID,DATASET_ID, TEXT_MODEL_NAME, PROJECT_ID,DATASET_ID )
    df = client.query(sql).to_dataframe()

except Exception as e:
    raise Exception(str(e))

df.head()

,Original Input,Classified Name,Confidence
0,try factory where UN peacekeepers were sta-\nt...,Sensitive Subjects,0.80000001
1,THE CORSICAN CAPER\nlove at first bite. Elena ...,Food & DrinkCooking & Recipes,0.56
2,GIANTS\n軍\nShawn Estes\nSAN FRANCISCO GIANTS: ...,SportsTeam SportsBaseball,0.98000002
3,Bryce Canyon National Park\nLodge\n♦\n0.5 mi\n...,TravelTourist DestinationsRegional Parks & Gar...,0.95999998
4,For ticket information FM\nAnnual\nAf\nommage ...,Arts & EntertainmentMusic & AudioClassical Music,0.91000003

In [50]:
#Use vision ai to get text from images
#then use translate ai to check language of text
try:
    client = bigquery.Client(project=PROJECT_ID)
    sql = f"""

CREATE OR REPLACE TABLE
 `{DATASET_ID}.temp_summarize` 
 AS
SELECT
  ml_generate_text_result['predictions'][0]['content'] AS generated_text,
  ml_generate_text_result['predictions'][0]['safetyAttributes'] AS safety_attributes,
  ml_generate_text_result['predictions'][0]['safetyAttributes']['blocked'] AS blocked,
  
  * EXCEPT (ml_generate_text_result)
FROM
  ML.GENERATE_TEXT( MODEL `{DATASET_ID}.llm_model`,
    (
    SELECT
      CONCAT('summarize: ', text_content) AS prompt,
      *
    FROM
      {DATASET_ID}.temp_image_results
    LIMIT
      5 ),
    STRUCT( 0.2 AS temperature,
      100 AS max_output_tokens));




SELECT  *
 FROM `{DATASET_ID}.temp_summarize` 
 
 """

    df = client.query(sql).to_dataframe()

except Exception as e:
    raise Exception(str(e))



df.head(6)

,generated_text,safety_attributes,blocked,ml_generate_text_status,prompt,text_content
0,"""The product is Coca-Cola Zero. It is a zero c...","{""blocked"":false,""categories"":[""Health"",""Illic...",false,,summarize: Ica-Colica Collca-Colca Col\nzero z...,Ica-Colica Collca-Colca Col\nzero zero zero ze...
1,"""sway The data is about a company's business. ...","{""blocked"":false,""categories"":[""Finance"",""Lega...",false,,summarize: Airport\nBusiness\n기\nunagroup\nCen...,Airport\nBusiness\n기\nunagroup\nCentre\nPlymou...
2,"""This is an article about Playmate of the Year...","{""blocked"":false,""categories"":[""Death, Harm & ...",false,,summarize: COMPANY B\n126M AGM 505 IME VE\nAbo...,COMPANY B\n126M AGM 505 IME VE\nAbove: Aboord ...
3,"""This is a book cover for a mystery novel call...","{""blocked"":false,""categories"":[""Finance"",""Illi...",false,,summarize: DELL\nD292\nTWO MIKE SHAYNE\nMYSTER...,DELL\nD292\nTWO MIKE SHAYNE\nMYSTERIES\nDEAD\n...
4,"""""","{""blocked"":true}",true,,summarize: F FÜR TRÄUME\nFortsetzung von Seite...,F FÜR TRÄUME\nFortsetzung von Seite 304\nDie K...